### ISSUE TITLE
'''Configure django-multisite as documented upstream'''

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-multisite#13]
The README says:

> Configure django-multisite as documented upstream

What's about to insert a link to: https://github.com/ecometrica/django-multisite#readme

Or what's about to add all needed settings in the local README?

**Comment by yakky** [comment]
Hi @jedie #20 should provide a much improved documentation about configuring this

**Comment by lcfd** [comment]
@yakky can we close it?
