### ISSUE TITLE
Is it compatible with DjangoCMS 3.6/3.7 or have it in mind?

### ISSUE THREAD

**Issue by JustDevZero** [nephila/djangocms-multisite#25]
Hi there,

Just found that app and found it really interesting, but...

I've seen that in tox that you were checking against BETA, but it's been awhile djangocms3.6 it's no more beta but STABLE and 3.7 it's going to release the old 3.4 LTS.

So... Do you have in mind to add compatibility to those versions?

**Comment by yakky** [comment]
Hi, sorry for the super late reply, version 0.3 will be released shortly with Django 2.2+ and django CMS 3.7+ support
