### ISSUE TITLE
Multisite with aldryn-newsblog?

### ISSUE THREAD

**Issue by bartmika** [nephila/djangocms-multisite#5]
Question, what would be a good strategy for changing the blog templates based on the site being visited using the https://github.com/aldryn/aldryn-newsblog library?

**Comment by yakky** [comment]
IIRC aldryn-newsblog (and djangocms-blog) has a field in the apphook configuration to provide a path for templates so that each instance of the blog can have its own set of templates

**Comment by bartmika** [comment]
Thanks @yakky! Will investigate further.
