### ISSUE TITLE
Django-CMS Domain Name not showing in menu.

### ISSUE THREAD

**Issue by bartmika** [nephila/djangocms-multisite#7]
**Problem**
I've created the following sites:
![screen shot 2016-06-22 at 7 40 32 am](https://cloud.githubusercontent.com/assets/5767602/16265328/befd356a-384c-11e6-8f44-1df142719ebf.png)

When I go to **example.com** my menu looks like this:
![screen shot 2016-06-22 at 7 38 22 am](https://cloud.githubusercontent.com/assets/5767602/16265344/d07f42ec-384c-11e6-8df5-d57bcc18e34f.png)

When I go to **example2.com** my menu looks like this:
![screen shot 2016-06-22 at 7 40 10 am](https://cloud.githubusercontent.com/assets/5767602/16265354/dcbb7166-384c-11e6-93cd-e8b75d8e566f.png)
(Notice: The 'example.com' is not being replaced with 'example2.com'.)

**Comment by yakky** [comment]
@bartmika Sorry it took so long to tackle this.
Please check this README change 1283d31: the order of middleware matters.
